server:
  port: '8080'
---
spring:
  profiles:
    active: dev
--- #??
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlserver://wizis.iptime.org:20220;databaseName=MES_ShinYoungInd;encrypt=true;trustServerCertificate=true
    username: dbuser
    password: Wizardis
--- #??
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: dbuser
    password: Wizardis
    url: jdbc:sqlserver://192.168.0.61:2433;databaseName=MES_ShinYoungInd;encrypt=true;trustServerCertificate=true
---
spring:
  devtools:
    remote:
      restart:
        enabled: 'true'
    livereload:
      enabled: 'true'
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  application:
    name: ShinYoungInd_Web
  thymeleaf:
    cache: 'false'
    enabled: 'true'
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
---
logging:
  level:
    org:
      springframework:
        security: DEBUG
---
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
---
